services:
  app:
    build:
      context: .
      dockerfile: ./packages/backend/Dockerfile
    ports:
      - "3000:8080"
    env_file:
      - ./packages/backend/.env.local
    depends_on:
      - firestore
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/webhook/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

  firestore:
    build:
      context: ./infra/emulator/firebase
      dockerfile: Dockerfile
    ports:
      - "8081:8081"  # Firestore emulator
      - "4000:4000"  # Firebase UI
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s